#!/bin/sh

rm -rf /tmp/clojure
git clone git://github.com/richhickey/clojure.git /tmp/clojure
(cd /tmp/clojure && ant jar && mv *.jar $CLJ_JARS)

rm -rf /tmp/clojure-contrib
git clone git://github.com/richhickey/clojure-contrib.git /tmp/clojure-contrib
#svn checkout http://clojure-contrib.googlecode.com/svn/trunk/ /tmp/clojure-contrib
(cd /tmp/clojure-contrib && ant jar && mv *.jar $CLJ_JARS)
